/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as PublicRouteImport } from './../pages/_public'
import { Route as ProtectedRouteImport } from './../pages/_protected'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as ApiPingRouteImport } from './../pages/api/ping'
import { Route as ApiCoverageRouteImport } from './../pages/api/coverage'
import { Route as PublicVoidAccountRouteImport } from './../pages/_public/void-account'
import { Route as PublicResetPasswordRouteImport } from './../pages/_public/reset-password'
import { Route as PublicRegisterRouteImport } from './../pages/_public/register'
import { Route as PublicPlaygroundRouteImport } from './../pages/_public/playground'
import { Route as PublicLoginRouteImport } from './../pages/_public/login'
import { Route as PublicConfirmEmailRouteImport } from './../pages/_public/confirm-email'
import { Route as ProtectedSettingsRouteImport } from './../pages/_protected/settings'
import { Route as ProtectedAdminRouteImport } from './../pages/_protected/admin'
import { Route as ProtectedAccountRouteImport } from './../pages/_protected/account'
import { Route as ProtectedReceiptsIndexRouteImport } from './../pages/_protected/receipts/index'
import { Route as ProtectedPeersIndexRouteImport } from './../pages/_protected/peers/index'
import { Route as ProtectedDebtsIndexRouteImport } from './../pages/_protected/debts/index'
import { Route as ApiUtilsPingCacheRouteImport } from './../pages/api/utils/ping-cache'
import { Route as ApiUtilsCleanupRouteImport } from './../pages/api/utils/cleanup'
import { Route as ApiTrpcSplatRouteImport } from './../pages/api/trpc/$'
import { Route as ProtectedReceiptsAddRouteImport } from './../pages/_protected/receipts/add'
import { Route as ProtectedReceiptsIdRouteImport } from './../pages/_protected/receipts/$id'
import { Route as ProtectedPeersConnectionsRouteImport } from './../pages/_protected/peers/connections'
import { Route as ProtectedPeersAddRouteImport } from './../pages/_protected/peers/add'
import { Route as ProtectedPeersIdRouteImport } from './../pages/_protected/peers/$id'
import { Route as ProtectedDebtsTransferRouteImport } from './../pages/_protected/debts/transfer'
import { Route as ProtectedDebtsIntentionsRouteImport } from './../pages/_protected/debts/intentions'
import { Route as ProtectedDebtsAddRouteImport } from './../pages/_protected/debts/add'
import { Route as ProtectedDebtsIdRouteImport } from './../pages/_protected/debts/$id'
import { Route as ProtectedDebtsPeerIdIndexRouteImport } from './../pages/_protected/debts/peer/$id/index'
import { Route as ProtectedDebtsPeerIdExchangeIndexRouteImport } from './../pages/_protected/debts/peer/$id/exchange/index'
import { Route as ProtectedDebtsPeerIdExchangeSpecificRouteImport } from './../pages/_protected/debts/peer/$id/exchange/specific'
import { Route as ProtectedDebtsPeerIdExchangeAllRouteImport } from './../pages/_protected/debts/peer/$id/exchange/all'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverageRoute = ApiCoverageRouteImport.update({
  id: '/api/coverage',
  path: '/api/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVoidAccountRoute = PublicVoidAccountRouteImport.update({
  id: '/void-account',
  path: '/void-account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlaygroundRoute = PublicPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfirmEmailRoute = PublicConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReceiptsIndexRoute = ProtectedReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeersIndexRoute = ProtectedPeersIndexRouteImport.update({
  id: '/peers/',
  path: '/peers/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebtsIndexRoute = ProtectedDebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiUtilsPingCacheRoute = ApiUtilsPingCacheRouteImport.update({
  id: '/api/utils/ping-cache',
  path: '/api/utils/ping-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUtilsCleanupRoute = ApiUtilsCleanupRouteImport.update({
  id: '/api/utils/cleanup',
  path: '/api/utils/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReceiptsAddRoute = ProtectedReceiptsAddRouteImport.update({
  id: '/receipts/add',
  path: '/receipts/add',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReceiptsIdRoute = ProtectedReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeersConnectionsRoute =
  ProtectedPeersConnectionsRouteImport.update({
    id: '/peers/connections',
    path: '/peers/connections',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPeersAddRoute = ProtectedPeersAddRouteImport.update({
  id: '/peers/add',
  path: '/peers/add',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeersIdRoute = ProtectedPeersIdRouteImport.update({
  id: '/peers/$id',
  path: '/peers/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebtsTransferRoute = ProtectedDebtsTransferRouteImport.update({
  id: '/debts/transfer',
  path: '/debts/transfer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebtsIntentionsRoute =
  ProtectedDebtsIntentionsRouteImport.update({
    id: '/debts/intentions',
    path: '/debts/intentions',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDebtsAddRoute = ProtectedDebtsAddRouteImport.update({
  id: '/debts/add',
  path: '/debts/add',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebtsIdRoute = ProtectedDebtsIdRouteImport.update({
  id: '/debts/$id',
  path: '/debts/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebtsPeerIdIndexRoute =
  ProtectedDebtsPeerIdIndexRouteImport.update({
    id: '/debts/peer/$id/',
    path: '/debts/peer/$id/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDebtsPeerIdExchangeIndexRoute =
  ProtectedDebtsPeerIdExchangeIndexRouteImport.update({
    id: '/debts/peer/$id/exchange/',
    path: '/debts/peer/$id/exchange/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDebtsPeerIdExchangeSpecificRoute =
  ProtectedDebtsPeerIdExchangeSpecificRouteImport.update({
    id: '/debts/peer/$id/exchange/specific',
    path: '/debts/peer/$id/exchange/specific',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDebtsPeerIdExchangeAllRoute =
  ProtectedDebtsPeerIdExchangeAllRouteImport.update({
    id: '/debts/peer/$id/exchange/all',
    path: '/debts/peer/$id/exchange/all',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRoute
  '/admin': typeof ProtectedAdminRoute
  '/settings': typeof ProtectedSettingsRoute
  '/confirm-email': typeof PublicConfirmEmailRoute
  '/login': typeof PublicLoginRoute
  '/playground': typeof PublicPlaygroundRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/void-account': typeof PublicVoidAccountRoute
  '/api/coverage': typeof ApiCoverageRoute
  '/api/ping': typeof ApiPingRoute
  '/debts/$id': typeof ProtectedDebtsIdRoute
  '/debts/add': typeof ProtectedDebtsAddRoute
  '/debts/intentions': typeof ProtectedDebtsIntentionsRoute
  '/debts/transfer': typeof ProtectedDebtsTransferRoute
  '/peers/$id': typeof ProtectedPeersIdRoute
  '/peers/add': typeof ProtectedPeersAddRoute
  '/peers/connections': typeof ProtectedPeersConnectionsRoute
  '/receipts/$id': typeof ProtectedReceiptsIdRoute
  '/receipts/add': typeof ProtectedReceiptsAddRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/utils/cleanup': typeof ApiUtilsCleanupRoute
  '/api/utils/ping-cache': typeof ApiUtilsPingCacheRoute
  '/debts/': typeof ProtectedDebtsIndexRoute
  '/peers/': typeof ProtectedPeersIndexRoute
  '/receipts/': typeof ProtectedReceiptsIndexRoute
  '/debts/peer/$id/': typeof ProtectedDebtsPeerIdIndexRoute
  '/debts/peer/$id/exchange/all': typeof ProtectedDebtsPeerIdExchangeAllRoute
  '/debts/peer/$id/exchange/specific': typeof ProtectedDebtsPeerIdExchangeSpecificRoute
  '/debts/peer/$id/exchange/': typeof ProtectedDebtsPeerIdExchangeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof ProtectedAccountRoute
  '/admin': typeof ProtectedAdminRoute
  '/settings': typeof ProtectedSettingsRoute
  '/confirm-email': typeof PublicConfirmEmailRoute
  '/login': typeof PublicLoginRoute
  '/playground': typeof PublicPlaygroundRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/void-account': typeof PublicVoidAccountRoute
  '/api/coverage': typeof ApiCoverageRoute
  '/api/ping': typeof ApiPingRoute
  '/debts/$id': typeof ProtectedDebtsIdRoute
  '/debts/add': typeof ProtectedDebtsAddRoute
  '/debts/intentions': typeof ProtectedDebtsIntentionsRoute
  '/debts/transfer': typeof ProtectedDebtsTransferRoute
  '/peers/$id': typeof ProtectedPeersIdRoute
  '/peers/add': typeof ProtectedPeersAddRoute
  '/peers/connections': typeof ProtectedPeersConnectionsRoute
  '/receipts/$id': typeof ProtectedReceiptsIdRoute
  '/receipts/add': typeof ProtectedReceiptsAddRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/utils/cleanup': typeof ApiUtilsCleanupRoute
  '/api/utils/ping-cache': typeof ApiUtilsPingCacheRoute
  '/debts': typeof ProtectedDebtsIndexRoute
  '/peers': typeof ProtectedPeersIndexRoute
  '/receipts': typeof ProtectedReceiptsIndexRoute
  '/debts/peer/$id': typeof ProtectedDebtsPeerIdIndexRoute
  '/debts/peer/$id/exchange/all': typeof ProtectedDebtsPeerIdExchangeAllRoute
  '/debts/peer/$id/exchange/specific': typeof ProtectedDebtsPeerIdExchangeSpecificRoute
  '/debts/peer/$id/exchange': typeof ProtectedDebtsPeerIdExchangeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/confirm-email': typeof PublicConfirmEmailRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/playground': typeof PublicPlaygroundRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/void-account': typeof PublicVoidAccountRoute
  '/api/coverage': typeof ApiCoverageRoute
  '/api/ping': typeof ApiPingRoute
  '/_protected/debts/$id': typeof ProtectedDebtsIdRoute
  '/_protected/debts/add': typeof ProtectedDebtsAddRoute
  '/_protected/debts/intentions': typeof ProtectedDebtsIntentionsRoute
  '/_protected/debts/transfer': typeof ProtectedDebtsTransferRoute
  '/_protected/peers/$id': typeof ProtectedPeersIdRoute
  '/_protected/peers/add': typeof ProtectedPeersAddRoute
  '/_protected/peers/connections': typeof ProtectedPeersConnectionsRoute
  '/_protected/receipts/$id': typeof ProtectedReceiptsIdRoute
  '/_protected/receipts/add': typeof ProtectedReceiptsAddRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/utils/cleanup': typeof ApiUtilsCleanupRoute
  '/api/utils/ping-cache': typeof ApiUtilsPingCacheRoute
  '/_protected/debts/': typeof ProtectedDebtsIndexRoute
  '/_protected/peers/': typeof ProtectedPeersIndexRoute
  '/_protected/receipts/': typeof ProtectedReceiptsIndexRoute
  '/_protected/debts/peer/$id/': typeof ProtectedDebtsPeerIdIndexRoute
  '/_protected/debts/peer/$id/exchange/all': typeof ProtectedDebtsPeerIdExchangeAllRoute
  '/_protected/debts/peer/$id/exchange/specific': typeof ProtectedDebtsPeerIdExchangeSpecificRoute
  '/_protected/debts/peer/$id/exchange/': typeof ProtectedDebtsPeerIdExchangeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/settings'
    | '/confirm-email'
    | '/login'
    | '/playground'
    | '/register'
    | '/reset-password'
    | '/void-account'
    | '/api/coverage'
    | '/api/ping'
    | '/debts/$id'
    | '/debts/add'
    | '/debts/intentions'
    | '/debts/transfer'
    | '/peers/$id'
    | '/peers/add'
    | '/peers/connections'
    | '/receipts/$id'
    | '/receipts/add'
    | '/api/trpc/$'
    | '/api/utils/cleanup'
    | '/api/utils/ping-cache'
    | '/debts/'
    | '/peers/'
    | '/receipts/'
    | '/debts/peer/$id/'
    | '/debts/peer/$id/exchange/all'
    | '/debts/peer/$id/exchange/specific'
    | '/debts/peer/$id/exchange/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/settings'
    | '/confirm-email'
    | '/login'
    | '/playground'
    | '/register'
    | '/reset-password'
    | '/void-account'
    | '/api/coverage'
    | '/api/ping'
    | '/debts/$id'
    | '/debts/add'
    | '/debts/intentions'
    | '/debts/transfer'
    | '/peers/$id'
    | '/peers/add'
    | '/peers/connections'
    | '/receipts/$id'
    | '/receipts/add'
    | '/api/trpc/$'
    | '/api/utils/cleanup'
    | '/api/utils/ping-cache'
    | '/debts'
    | '/peers'
    | '/receipts'
    | '/debts/peer/$id'
    | '/debts/peer/$id/exchange/all'
    | '/debts/peer/$id/exchange/specific'
    | '/debts/peer/$id/exchange'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/account'
    | '/_protected/admin'
    | '/_protected/settings'
    | '/_public/confirm-email'
    | '/_public/login'
    | '/_public/playground'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_public/void-account'
    | '/api/coverage'
    | '/api/ping'
    | '/_protected/debts/$id'
    | '/_protected/debts/add'
    | '/_protected/debts/intentions'
    | '/_protected/debts/transfer'
    | '/_protected/peers/$id'
    | '/_protected/peers/add'
    | '/_protected/peers/connections'
    | '/_protected/receipts/$id'
    | '/_protected/receipts/add'
    | '/api/trpc/$'
    | '/api/utils/cleanup'
    | '/api/utils/ping-cache'
    | '/_protected/debts/'
    | '/_protected/peers/'
    | '/_protected/receipts/'
    | '/_protected/debts/peer/$id/'
    | '/_protected/debts/peer/$id/exchange/all'
    | '/_protected/debts/peer/$id/exchange/specific'
    | '/_protected/debts/peer/$id/exchange/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiCoverageRoute: typeof ApiCoverageRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUtilsCleanupRoute: typeof ApiUtilsCleanupRoute
  ApiUtilsPingCacheRoute: typeof ApiUtilsPingCacheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coverage': {
      id: '/api/coverage'
      path: '/api/coverage'
      fullPath: '/api/coverage'
      preLoaderRoute: typeof ApiCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/void-account': {
      id: '/_public/void-account'
      path: '/void-account'
      fullPath: '/void-account'
      preLoaderRoute: typeof PublicVoidAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/playground': {
      id: '/_public/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PublicPlaygroundRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/confirm-email': {
      id: '/_public/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof PublicConfirmEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/receipts/': {
      id: '/_protected/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ProtectedReceiptsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/peers/': {
      id: '/_protected/peers/'
      path: '/peers'
      fullPath: '/peers/'
      preLoaderRoute: typeof ProtectedPeersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/': {
      id: '/_protected/debts/'
      path: '/debts'
      fullPath: '/debts/'
      preLoaderRoute: typeof ProtectedDebtsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/utils/ping-cache': {
      id: '/api/utils/ping-cache'
      path: '/api/utils/ping-cache'
      fullPath: '/api/utils/ping-cache'
      preLoaderRoute: typeof ApiUtilsPingCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/utils/cleanup': {
      id: '/api/utils/cleanup'
      path: '/api/utils/cleanup'
      fullPath: '/api/utils/cleanup'
      preLoaderRoute: typeof ApiUtilsCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/receipts/add': {
      id: '/_protected/receipts/add'
      path: '/receipts/add'
      fullPath: '/receipts/add'
      preLoaderRoute: typeof ProtectedReceiptsAddRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/receipts/$id': {
      id: '/_protected/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ProtectedReceiptsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/peers/connections': {
      id: '/_protected/peers/connections'
      path: '/peers/connections'
      fullPath: '/peers/connections'
      preLoaderRoute: typeof ProtectedPeersConnectionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/peers/add': {
      id: '/_protected/peers/add'
      path: '/peers/add'
      fullPath: '/peers/add'
      preLoaderRoute: typeof ProtectedPeersAddRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/peers/$id': {
      id: '/_protected/peers/$id'
      path: '/peers/$id'
      fullPath: '/peers/$id'
      preLoaderRoute: typeof ProtectedPeersIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/transfer': {
      id: '/_protected/debts/transfer'
      path: '/debts/transfer'
      fullPath: '/debts/transfer'
      preLoaderRoute: typeof ProtectedDebtsTransferRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/intentions': {
      id: '/_protected/debts/intentions'
      path: '/debts/intentions'
      fullPath: '/debts/intentions'
      preLoaderRoute: typeof ProtectedDebtsIntentionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/add': {
      id: '/_protected/debts/add'
      path: '/debts/add'
      fullPath: '/debts/add'
      preLoaderRoute: typeof ProtectedDebtsAddRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/$id': {
      id: '/_protected/debts/$id'
      path: '/debts/$id'
      fullPath: '/debts/$id'
      preLoaderRoute: typeof ProtectedDebtsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/peer/$id/': {
      id: '/_protected/debts/peer/$id/'
      path: '/debts/peer/$id'
      fullPath: '/debts/peer/$id/'
      preLoaderRoute: typeof ProtectedDebtsPeerIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/peer/$id/exchange/': {
      id: '/_protected/debts/peer/$id/exchange/'
      path: '/debts/peer/$id/exchange'
      fullPath: '/debts/peer/$id/exchange/'
      preLoaderRoute: typeof ProtectedDebtsPeerIdExchangeIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/peer/$id/exchange/specific': {
      id: '/_protected/debts/peer/$id/exchange/specific'
      path: '/debts/peer/$id/exchange/specific'
      fullPath: '/debts/peer/$id/exchange/specific'
      preLoaderRoute: typeof ProtectedDebtsPeerIdExchangeSpecificRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debts/peer/$id/exchange/all': {
      id: '/_protected/debts/peer/$id/exchange/all'
      path: '/debts/peer/$id/exchange/all'
      fullPath: '/debts/peer/$id/exchange/all'
      preLoaderRoute: typeof ProtectedDebtsPeerIdExchangeAllRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedDebtsIdRoute: typeof ProtectedDebtsIdRoute
  ProtectedDebtsAddRoute: typeof ProtectedDebtsAddRoute
  ProtectedDebtsIntentionsRoute: typeof ProtectedDebtsIntentionsRoute
  ProtectedDebtsTransferRoute: typeof ProtectedDebtsTransferRoute
  ProtectedPeersIdRoute: typeof ProtectedPeersIdRoute
  ProtectedPeersAddRoute: typeof ProtectedPeersAddRoute
  ProtectedPeersConnectionsRoute: typeof ProtectedPeersConnectionsRoute
  ProtectedReceiptsIdRoute: typeof ProtectedReceiptsIdRoute
  ProtectedReceiptsAddRoute: typeof ProtectedReceiptsAddRoute
  ProtectedDebtsIndexRoute: typeof ProtectedDebtsIndexRoute
  ProtectedPeersIndexRoute: typeof ProtectedPeersIndexRoute
  ProtectedReceiptsIndexRoute: typeof ProtectedReceiptsIndexRoute
  ProtectedDebtsPeerIdIndexRoute: typeof ProtectedDebtsPeerIdIndexRoute
  ProtectedDebtsPeerIdExchangeAllRoute: typeof ProtectedDebtsPeerIdExchangeAllRoute
  ProtectedDebtsPeerIdExchangeSpecificRoute: typeof ProtectedDebtsPeerIdExchangeSpecificRoute
  ProtectedDebtsPeerIdExchangeIndexRoute: typeof ProtectedDebtsPeerIdExchangeIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedDebtsIdRoute: ProtectedDebtsIdRoute,
  ProtectedDebtsAddRoute: ProtectedDebtsAddRoute,
  ProtectedDebtsIntentionsRoute: ProtectedDebtsIntentionsRoute,
  ProtectedDebtsTransferRoute: ProtectedDebtsTransferRoute,
  ProtectedPeersIdRoute: ProtectedPeersIdRoute,
  ProtectedPeersAddRoute: ProtectedPeersAddRoute,
  ProtectedPeersConnectionsRoute: ProtectedPeersConnectionsRoute,
  ProtectedReceiptsIdRoute: ProtectedReceiptsIdRoute,
  ProtectedReceiptsAddRoute: ProtectedReceiptsAddRoute,
  ProtectedDebtsIndexRoute: ProtectedDebtsIndexRoute,
  ProtectedPeersIndexRoute: ProtectedPeersIndexRoute,
  ProtectedReceiptsIndexRoute: ProtectedReceiptsIndexRoute,
  ProtectedDebtsPeerIdIndexRoute: ProtectedDebtsPeerIdIndexRoute,
  ProtectedDebtsPeerIdExchangeAllRoute: ProtectedDebtsPeerIdExchangeAllRoute,
  ProtectedDebtsPeerIdExchangeSpecificRoute:
    ProtectedDebtsPeerIdExchangeSpecificRoute,
  ProtectedDebtsPeerIdExchangeIndexRoute:
    ProtectedDebtsPeerIdExchangeIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicConfirmEmailRoute: typeof PublicConfirmEmailRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPlaygroundRoute: typeof PublicPlaygroundRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVoidAccountRoute: typeof PublicVoidAccountRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicConfirmEmailRoute: PublicConfirmEmailRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPlaygroundRoute: PublicPlaygroundRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVoidAccountRoute: PublicVoidAccountRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiCoverageRoute: ApiCoverageRoute,
  ApiPingRoute: ApiPingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUtilsCleanupRoute: ApiUtilsCleanupRoute,
  ApiUtilsPingCacheRoute: ApiUtilsPingCacheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
