compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: patches

supportedArchitectures:
  cpu:
    - current
    # Both CI and local development run on Linux
    - arm64
  os:
    - current
    # CI runs on Linux
    - linux
    # Local development runs on MacOS
    - darwin
# Yarn path is appended here in Vercel install step because of the bug
# See: https://github.com/yarnpkg/berry/issues/5831

catalog:
  cookie: ^1.0.2
  i18next: ^25.8.0
  dataloader: ^2.2.2
  react-i18next: ^16.5.4
  tailwindcss: ^4.1.14
  uniwind: ^1.2.2
  uuid: ^9.0.0
  timekeeper: ^2.3.1
  heroui-native: ^1.0.0-beta.12
  "@types/uuid": ^9.0.2
  zod: ^4.0.5
  sharp: ^0.32.6
  react: 19.2.0
  react-dom: 19.2.0
  tsx: ^4.21.0
  expo-router: ~55.0.0-preview.6
  babel-plugin-react-compiler: ^1.0.0
  "@heroui/react": ^2.8.4
  "@trpc/react-query": ^11.9.0
  "@trpc/client": ^11.9.0
  "@trpc/server": ^11.9.0
  "@trpc/tanstack-react-query": ^11.9.0
  "@tanstack/react-router": ^1.131.49
  "@tanstack/react-query": 5.80.6
  "@tanstack/react-query-devtools": 5.80.6
