compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: patches

supportedArchitectures:
  cpu:
    - current
    # Both CI and local development run on Linux
    - arm64
  os:
    - current
    # CI runs on Linux
    - linux
    # Local development runs on MacOS
    - darwin
# Yarn path is appended here in Vercel install step because of the bug
# See: https://github.com/yarnpkg/berry/issues/5831
