compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: patches

supportedArchitectures:
  cpu:
    - current
    - arm64
  os:
    - current
    - linux
# Yarn path is appended here in Vercel install step because of the bug
# See: https://github.com/yarnpkg/berry/issues/5831
