compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: patches

supportedArchitectures:
  cpu:
    - current
    # Both CI and local development run on Linux
    - arm64
  os:
    - current
    # CI runs on Linux
    - linux
    # Local development runs on MacOS
    - darwin
# Yarn path is appended here in Vercel install step because of the bug
# See: https://github.com/yarnpkg/berry/issues/5831

catalog:
  cookie: ^1.0.2
  i18next: ^25.2.1
  dataloader: ^2.2.2
  react-i18next: ^15.5.3
  tailwindcss: ^4.1.14
  uniwind: ^1.2.2
  uuid: ^9.0.0
  timekeeper: ^2.3.1
  "@types/uuid": ^9.0.2
  zod: ^4.0.5
  sharp: ^0.32.6
  "@trpc/react-query": ^11.4.3
  "@trpc/client": ^11.4.3
  "@trpc/server": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  "@tanstack/react-query": 5.80.6
  "@tanstack/react-query-devtools": 5.80.6
  "@tanstack/query-async-storage-persister": 5.80.6
