/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { CurrencyCode } from "~app/utils/currency";
import type { DebtId, PeerId, ReceiptId, ReceiptItemId, SessionId, UserId } from "~db/ids";
import type { ColumnType } from "kysely";

export type Consumetype = "amount" | "parts" | "percent";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Receiptrole = "editor" | "owner" | "viewer";

export interface Debt {
  amount: Numeric;
  createdAt: Generated<Temporal.ZonedDateTime>;
  currencyCode: CurrencyCode;
  id: DebtId;
  note: string;
  ownerUserId: UserId;
  peerId: PeerId;
  receiptId: ReceiptId | null;
  timestamp: Temporal.PlainDate;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface Peer {
  acceptReceipts: Generated<boolean>;
  connectedUserId: UserId | null;
  createdAt: Generated<Temporal.ZonedDateTime>;
  exposeReceipts: Generated<boolean>;
  id: PeerId;
  name: string;
  ownerUserId: UserId;
  publicName: string | null;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ReceiptItemConsumer {
  createdAt: Generated<Temporal.ZonedDateTime>;
  itemId: ReceiptItemId;
  part: Numeric;
  peerId: PeerId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ReceiptItemPayer {
  createdAt: Generated<Temporal.ZonedDateTime>;
  itemId: ReceiptItemId;
  part: Numeric;
  peerId: PeerId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ReceiptItem {
  consumeType: Consumetype | null;
  createdAt: Generated<Temporal.ZonedDateTime>;
  id: ReceiptItemId;
  name: string;
  price: Numeric;
  quantity: Numeric;
  receiptId: ReceiptId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ReceiptParticipant {
  createdAt: Generated<Temporal.ZonedDateTime>;
  peerId: PeerId;
  receiptId: ReceiptId;
  role: Receiptrole;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface Receipt {
  consumeType: Generated<Consumetype>;
  createdAt: Generated<Temporal.ZonedDateTime>;
  currencyCode: CurrencyCode;
  id: ReceiptId;
  issued: Temporal.PlainDate;
  name: string;
  ownerUserId: UserId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ResetPasswordIntention {
  createdAt: Generated<Temporal.ZonedDateTime>;
  expiresTimestamp: Temporal.ZonedDateTime;
  token: string;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface Session {
  createdAt: Generated<Temporal.ZonedDateTime>;
  expirationTimestamp: Temporal.ZonedDateTime;
  sessionId: SessionId;
  userId: UserId;
}

export interface User {
  avatarUrl: string | null;
  confirmationToken: string | null;
  confirmationTokenTimestamp: Temporal.ZonedDateTime | null;
  createdAt: Generated<Temporal.ZonedDateTime>;
  email: string;
  id: UserId;
  passwordHash: string;
  passwordSalt: string;
  role: string | null;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface UserSetting {
  manualAcceptDebts: boolean;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface DB {
  debts: Debt;
  peers: Peer;
  receiptItemConsumers: ReceiptItemConsumer;
  receiptItemPayers: ReceiptItemPayer;
  receiptItems: ReceiptItem;
  receiptParticipants: ReceiptParticipant;
  receipts: Receipt;
  resetPasswordIntentions: ResetPasswordIntention;
  sessions: Session;
  users: User;
  userSettings: UserSetting;
}
