/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { CurrencyCode } from "~app/utils/currency";
import type { AccountId, DebtId, ReceiptId, ReceiptItemId, SessionId, UserId } from "~db/ids";
import type { Temporal } from "~utils/date";
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export interface AccountConnectionsIntention {
  accountId: AccountId;
  createdAt: Generated<Temporal.ZonedDateTime>;
  targetAccountId: AccountId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface Account {
  avatarUrl: string | null;
  confirmationToken: string | null;
  confirmationTokenTimestamp: Temporal.ZonedDateTime | null;
  createdAt: Generated<Temporal.ZonedDateTime>;
  email: string;
  id: AccountId;
  passwordHash: string;
  passwordSalt: string;
  role: string | null;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface AccountSetting {
  accountId: AccountId;
  manualAcceptDebts: boolean;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface Debt {
  amount: Numeric;
  createdAt: Generated<Temporal.ZonedDateTime>;
  currencyCode: CurrencyCode;
  id: DebtId;
  note: string;
  ownerAccountId: AccountId;
  receiptId: ReceiptId | null;
  timestamp: Temporal.PlainDate;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface ReceiptItemConsumer {
  createdAt: Generated<Temporal.ZonedDateTime>;
  itemId: ReceiptItemId;
  part: Numeric;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface ReceiptItemPayer {
  createdAt: Generated<Temporal.ZonedDateTime>;
  itemId: ReceiptItemId;
  part: Numeric;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface ReceiptItem {
  createdAt: Generated<Temporal.ZonedDateTime>;
  id: ReceiptItemId;
  name: string;
  price: Numeric;
  quantity: Numeric;
  receiptId: ReceiptId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ReceiptParticipant {
  createdAt: Generated<Temporal.ZonedDateTime>;
  receiptId: ReceiptId;
  role: string;
  updatedAt: Generated<Temporal.ZonedDateTime>;
  userId: UserId;
}

export interface Receipt {
  createdAt: Generated<Temporal.ZonedDateTime>;
  currencyCode: CurrencyCode;
  id: ReceiptId;
  issued: Temporal.PlainDate;
  name: string;
  ownerAccountId: AccountId;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface ResetPasswordIntention {
  accountId: AccountId;
  createdAt: Generated<Temporal.ZonedDateTime>;
  expiresTimestamp: Temporal.ZonedDateTime;
  token: string;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface Session {
  accountId: string;
  createdAt: Generated<Temporal.ZonedDateTime>;
  expirationTimestamp: Temporal.ZonedDateTime;
  sessionId: SessionId;
}

export interface User {
  acceptReceipts: Generated<boolean>;
  connectedAccountId: AccountId | null;
  createdAt: Generated<Temporal.ZonedDateTime>;
  exposeReceipts: Generated<boolean>;
  id: UserId;
  name: string;
  ownerAccountId: AccountId;
  publicName: string | null;
  updatedAt: Generated<Temporal.ZonedDateTime>;
}

export interface DB {
  accountConnectionsIntentions: AccountConnectionsIntention;
  accounts: Account;
  accountSettings: AccountSetting;
  debts: Debt;
  receiptItemConsumers: ReceiptItemConsumer;
  receiptItemPayers: ReceiptItemPayer;
  receiptItems: ReceiptItem;
  receiptParticipants: ReceiptParticipant;
  receipts: Receipt;
  resetPasswordIntentions: ResetPasswordIntention;
  sessions: Session;
  users: User;
}
