// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module "uniwind" {
	// Augmentation can only be done via interface
	export interface UniwindConfig {
		themes: readonly ["light", "dark"];
	}
}

// As intended by library
// eslint-disable-next-line unicorn/require-module-specifiers
export {};
