name: Setup node with .nvmrc
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: "yarn"
    - name: Yarn install
      run: yarn install && yarn postinstall
      shell: bash
